# Generated by Django 2.0.1 on 2018-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('Bronze', 'Bronze - $500'), ('Silver', 'Silver - $1000'), ('Gold', 'Gold - $2000'), ('Diamond', 'Diamond - $5000'), ('Other', 'Other')], max_length=15),
        ),
    ]
