# Generated by Django 2.0.1 on 2018-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20180420_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='contact_name',
        ),
    ]
