# Generated by Django 2.0.1 on 2018-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20180225_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website URL/ Twitter handle'),
        ),
    ]
