# Generated by Django 2.0.1 on 2018-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20180428_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
