# Generated by Django 2.0.1 on 2018-04-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20180412_0051'),
        ('sponsors', '0004_auto_20180416_1556'),
    ]

    operations = [
    ]
