# Generated by Django 2.0.1 on 2018-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20180416_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, default='', help_text='website URL/ Twitter handle'),
        ),
    ]
