# Generated by Django 2.0.1 on 2018-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_auto_20180428_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('Bronze', 'Bronze - $500'), ('Silver', 'Silver - $1000'), ('Gold', 'Gold - $2500'), ('Diamond', 'Diamond - $3500'), ('Special', 'Special'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('C', 'Corporate Sponsor'), ('S', 'Special Sponsor'), ('I', 'Individual Sponsor')], max_length=1, verbose_name='sponsor type'),
        ),
    ]
