# Generated by Django 2.0.1 on 2018-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_merge_20180417_1733'),
        ('sponsors', '0007_auto_20180418_0920'),
    ]

    operations = [
    ]
