# Generated by Django 2.0.1 on 2018-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0009_auto_20180428_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sponsors/'),
        ),
    ]
