# Generated by Django 2.0.1 on 2018-05-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_auto_20180428_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the Sponsor', null=True),
        ),
    ]
