# Generated by Django 2.0.1 on 2018-04-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatar.jpg', upload_to='media/avatars/'),
        ),
    ]
