# Generated by Django 2.0.1 on 2018-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180301_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='', help_text='A link to your Photo'),
        ),
    ]
