# Generated by Django 2.0.1 on 2018-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='', help_text='A link to your Photo, Your photo (not an illustration nor avatar):'),
        ),
    ]
