# Generated by Django 2.0.1 on 2018-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180303_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.URLField(blank=True, max_length=15, null=True),
        ),
    ]
