# Generated by Django 2.0.1 on 2018-02-15 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('registration', '0004_supervisedregistrationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(help_text='Tell us a bit about yourself and your work with Python', max_length=500)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('contact_number', models.CharField(help_text='Please include your country code.', max_length=16, null=True)),
                ('website', models.CharField(blank=True, help_text='Your website/blog URL.', max_length=255, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True)),
                ('github_username', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
