# Generated by Django 2.0.1 on 2018-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180307_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
