# Generated by Django 2.0.1 on 2018-03-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180307_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='surname',
        ),
    ]
