# Generated by Django 2.0.1 on 2018-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180428_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/avatar.jpg', max_length=255, null=True, upload_to='profile/avatars/'),
        ),
    ]
