# Generated by Django 2.0.1 on 2018-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.jpg', max_length=255, null=True, upload_to='profile/avatars/'),
        ),
    ]
