# Generated by Django 2.0.1 on 2018-02-15 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('title', models.CharField(max_length=1024)),
                ('talk_type', models.CharField(choices=[('Short Talk', 'Short Talk - 30 mins'), ('Long Talk', 'Long Talk - 1 hour'), ('Keynote', 'Keynote Talk - 45 mins')], max_length=20)),
                ('proposal_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('proposal', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Other Informations.', null=True)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('A', 'Accepted'), ('W', 'Waiting List'), ('R', 'Rejected')], default='', max_length=1)),
                ('programming_experience', models.CharField(choices=[('BP', 'Beginners'), ('IP', 'Intermediate Programmers'), ('SP', 'Senior Programmers'), ('EP', 'Expert Programmers')], default='', max_length=30)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
