# Generated by Django 2.0.1 on 2018-02-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
