# Generated by Django 2.0.1 on 2018-02-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20180228_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='extra_requirement',
            new_name='Anything_else_you_want_to_tell_us',
        ),
    ]
