# Generated by Django 2.0.1 on 2018-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20180228_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal',
            new_name='Tell_the_audience_about_your_talk',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='name',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Anything_else_you_want_to_tell_us',
            field=models.TextField(blank=True, default='', help_text='Kindly add anything else you want to tell us?.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='programming_experience',
            field=models.CharField(choices=[('BP', 'Beginners'), ('IP', 'Intermediate Programmers'), ('SP', 'Senior Programmers'), ('EP', 'Expert Programmers')], default='', help_text='Your targeted audience.', max_length=30),
        ),
    ]
