# Generated by Django 2.0.1 on 2018-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20180228_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='Tell_the_audience_about_your_talk',
            field=models.TextField(help_text='Describe your workshop or sprint. Please include the requirements: libraries and Python version to be installed, required experience with topics/libraries, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(help_text='Public title. What topic/project is it all about?', max_length=1024),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='url',
            field=models.URLField(default='', help_text='Got a video? If you have a recording of you giving a talk or leading a workshop, you can paste the link here.'),
        ),
    ]
