# Generated by Django 2.0.1 on 2018-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_auto_20180228_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='programming_experience',
            field=models.CharField(choices=[('BP', 'Beginners'), ('IP', 'Intermediate Programmers'), ('EP', 'Expert Programmers')], default='', help_text='Your targeted audience.', max_length=30),
        ),
    ]
