# Generated by Django 2.0.1 on 2018-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_auto_20180417_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Your Abstract.', null=True),
        ),
    ]
