# Generated by Django 2.0.1 on 2018-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_auto_20180418_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='recording_release',
            field=models.BooleanField(default=True),
        ),
    ]
