# Generated by Django 2.0.1 on 2018-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_proposal_recording_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('Short Talk', 'Short Talk - 30 mins'), ('Keynote', 'Keynote Talk - 45 mins')], max_length=20),
        ),
    ]
