# Generated by Django 2.0.1 on 2018-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_auto_20180419_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='notes',
            new_name='abstract',
        ),
    ]
