# Generated by Django 2.0.1 on 2018-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_auto_20180419_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='Tell_the_audience_about_your_talk',
            field=models.TextField(help_text='Describe your Talk to your targeted audience . Please include the requirements: libraries and Python version to be installed, required experience with topics/libraries, etc.', max_length=255),
        ),
    ]
