# Generated by Django 2.0.1 on 2018-04-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0017_auto_20180426_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='url',
        ),
    ]
