# Generated by Django 2.0.1 on 2018-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0018_auto_20180426_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='email',
            field=models.EmailField(default='', help_text='We’ll keep it secret, for internal use only.', max_length=1024),
        ),
        migrations.AddField(
            model_name='proposal',
            name='url',
            field=models.URLField(default='', help_text='Got a video? If you have a recording of you giving a talk or leading a workshop, you can paste the link here.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('Short Talk', 'Short Talk - 30 mins'), ('Long Talk', 'Long Talk - 45 mins')], max_length=20),
        ),
    ]
