# Generated by Django 2.0.1 on 2018-04-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0020_auto_20180426_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='email',
            field=models.EmailField(default=1, help_text='It will be kept secretly from the Public', max_length=254),
            preserve_default=False,
        ),
    ]
