# Generated by Django 2.0.1 on 2018-04-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0021_proposal_email'),
        ('talks', '0018_auto_20180425_2338'),
    ]

    operations = [
    ]
