# Generated by Django 2.0.1 on 2018-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0023_auto_20180428_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='intended_audience',
            field=models.CharField(choices=[('BP', 'Beginners, no prior knowledge of Python required'), ('IP', 'Intermediate Programmers, some prior knowledge of Python required'), ('EP', 'Expert Programmers, Experienced Python programmers level')], default='', help_text='Your targeted audience.', max_length=30),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('Short Talk', 'Short Talk - 30 mins'), ('Long Talk', 'Long Talk - 45 mins'), ('Tutorial', 'Tutorial - 2 hours or more')], max_length=20),
        ),
    ]
